seed: 42
device: cuda
wandb: True
wandb_entity: 'RookieVicky'
wandb_project: 'movie-recommendation'
run_name: ''
predict: False
checkpoint: 'saved/checkpoints/S3Rec_Ml.pt'
model: S3RecModel
log_freq: 100

dataloader:
    batch_size: 256

dataset:
    data_path: data/
    data_name: Ml

model_args:
    hidden_size: 64
    num_attention_heads: 2
    num_hidden_layers: 2
    hidden_act: gelu
    attention_probs_dropout_prob: 0.5
    hidden_dropout_prob: 0.5
    max_seq_length: 50
    S3RecModel:
        initializer_range: 0.02

optimizer:
    type: Adam
    args:
        lr: 1e-3
        weight_decay: 0.0
        adam_beta1: 0.9
        adam_beta2: 0.999

lr_scheduler:
    use: False
    type: ReduceLROnPlateau
    args:
        mode: 'min'
        factor: 0.1
        step_size: 10
        gamma: 0.1

train:
    epochs: 200
    log_path: saved/log
    ckpt_path: saved/checkpoint
    submit_path: saved/submit
    save_best_model: True
    resume: False
    resume_path: saved/checkpoint/S3Rec_Ml.pt

pretrain:
    epochs: 300
    batch_size: 512
    mask_probability: 0.2
    aap_weight: 0.2
    mip_weight: 1.0
    map_weight: 1.0
    sp_weight: 0.5